services:
  rpa:
    build:
      context: etl
      dockerfile: ../docker/rpa/Dockerfile
    container_name: rpa_service
    volumes:
      - ./etl:/app
    command: ["poetry", "run", "python", "main.py"]