services:
  etl:
    build:
      context: .
      dockerfile: ./docker/etl/Dockerfile
    container_name: etl
    volumes:
      - ./backend/etl:/app
      - /dev/shm:/dev/shm
    command: [ "poetry", "run", "python", "main.py" ]

  mongodb:
    image: mongo:6.0
    container_name: db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: juscash
    volumes:
      - ./docker/mongodb:/data/db


  #  frontend:
  #    build: ./docker/frontend
  #    container_name: frontend
  #    ports:
  #      - '3000:3000'
  #    volumes:
  #      - ./frontend:/app
  ##      - /app/node_modules
  #    environment:
  #      - CHOKIDAR_USEPOLLING=true