services:
  db:
    image: mongo:6.0
    container_name: db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: juscash
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - juscash

  etl:
    build:
      context: .
      dockerfile: ./docker/etl/Dockerfile
    container_name: etl
    volumes:
      - ./backend/etl:/app
      - /dev/shm:/dev/shm
    command: [ "poetry", "run", "python", "main.py" ]
    depends_on:
     - db
    networks:
      - juscash

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api:/app
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://admin:password@db:27017/juscash?authSource=admin"
      JWT_SECRET: "supersecretkey"
    depends_on:
      - db
    networks:
      - juscash

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - juscash

networks:
  juscash:
    driver: bridge