# Utiliza a imagem oficial do Node.js como base
FROM node:18-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependências para o contêiner
#COPY package*.json ./

# Instala as dependências
#RUN npm install

# Copia o restante do código da aplicação
#COPY . .

# Expõe a porta que a aplicação irá rodar
#EXPOSE 3000

# Comando para iniciar a aplicação
#CMD ["npm", "start"]